spring:
  application:
    name: card-service
  cloud:
    discovery:
      client:
        simple:
          instances:
            proxy:
              - uri: http://localhost:9083
            fraud-verifier:
              - uri: http://localhost:9981
            user-service:
              - uri: http://localhost:9082
    loadbalancer:
      eager-load:
        clients:
          - fraud-verifier
          - proxy
      #      clients:
      #        fraud-verifier:
      #          configurations: default
      #          retry:
      #            avoid-previous-instance: false
#      configurations: health-check
      retry:
        enabled: true
        retryable-status-codes: 503,404
        avoid-previous-instance: true
      ribbon:
        enabled: false
      zone: test
      sticky-session:
        add-service-instance-cookie: true
        instance-id-cookie-name:
      hint:
        default: test
      hint-header-name: X-Test
      health-check:
        refetch-instances: true
#      cache:
#        ttl: 60m
#        enabled: false
#        caffeine:
#          spec: maximumSize=200,expireAfterWrite=300s
logging:
  level:
    org.springframework: debug
    io.github.olgamaciaszek: debug
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health
  server:
    port: 8888
#eureka:
#  instance:
#    metadata-map:
#      zone: zone1
#  client:
#    healthcheck:
#      enabled: true

